#!/usr/bin/env bash
# usign dig with awk
array=( "www" "lb-01" "web-01" "web-02" )
str='{print " is a "$4 " record and points to " $5}'
if [ $# -eq 2 ] ; then
    echo -n "The subdomain $2"
    dig $2.$1| grep -A1 "ANSWER SECTION:" | tail -n 1 | awk str
else
    for i in "${array[@]}" ; do
	echo -n "The subdomain $i"
	dig $2.$1 | grep -A1 "ANSWER SECTION:" | tail -n 1 | awk str
    done
fi
