#!/usr/bin/env bash
#Process and PID file
sudo touch /var/run/myscript.pid
echo $$ >> sudo /var/run/myscript.pid
trap "exit_sigterm" SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap "exit_sigquit" SIGQUIT
exit_sigterm()
{
    echo "I hate the kill command"
    sudo rm /var/run/myscript.pid
    exit 1
}
exit_sigquit()
{
    sudo rm /var/run/myscript.pid
    exit 1
}
while ((1))
do
    echo "To infinity and beyond"
    sleep 2
done