#!/usr/bin/env bash
#Bash script that displays Best School 10 times using while
i="0"
text="Best School"
s="Hi"
while [ $i -lt 10 ]
do
    if [ $i -eq 9 ]
        then echo "$s"
    fi
    echo "$text"
       i=$(("$i" + 1))
 
done
